### ISSUE TITLE
Spider external urls

### ISSUE THREAD

**Issue by jarodium** [asika32764/php-sitemap#1]
Are you allowing external url's to be indexed as well?
It should provide an option to keep them from being indexed.

**Comment by asika32764** [comment]
I have no idea about the external URL you mentioned.

This package follows standard sitemap protocol http://www.sitemaps.org/protocol.html

If you need some extra attributes or parameters, you can do this:

``` php
$xml = $sitemap->getSimpleXmlElement();

$xml->children[0]['foo'] = 'bar';
```

**Comment by jarodium** [comment]
Hello 
Ill try to clear up this issue.

Lets us say i am indexing results from google.com, and only fromcgoogle.com.

I dont want urls from its results pages to be indexed, because they are external to google.con.

My question was if the spider will leave a given domain  when creating a sitemap

Thanks

**Comment by asika32764** [comment]
I think the purpose of what you want is impossible. As my knowledge, the standard sitmap protocol didn't includes any information about `not-indexed`, `nofollow` elements etc.

Your choice is that only do not add the external URLs to your sitemap.
